# Generated by Django 5.1.6 on 2025-03-16 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curricula', '0011_course_required_lab_course_required_math'),
        ('myprofile', '0016_phdstudent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConferencePublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True)),
                ('authors_list', models.TextField(null=True)),
                ('conference_name', models.CharField(null=True)),
                ('venue', models.CharField(null=True)),
                ('year', models.IntegerField(null=True)),
                ('has_supervisor', models.BooleanField(null=True)),
                ('candidate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myprofile.phdstudent')),
            ],
        ),
        migrations.CreateModel(
            name='JournalPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True)),
                ('authors_list', models.TextField(null=True)),
                ('has_supervisor', models.BooleanField(null=True)),
                ('journal', models.CharField(null=True)),
                ('publisher', models.CharField(null=True)),
                ('volume', models.CharField(null=True)),
                ('issue', models.CharField(null=True)),
                ('year', models.IntegerField(null=True)),
                ('doi', models.CharField(null=True)),
                ('candidate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myprofile.phdstudent')),
            ],
        ),
        migrations.CreateModel(
            name='Teaching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(null=True)),
                ('teaching_type', models.CharField(choices=[('Theory Lecture', 'Διάλεξη Θεωρίας'), ('Laboratory Course', 'Εργαστηριακό Μάθημα'), ('Assignment Correction', 'Διόρθωση Εργασίας'), ('Tutorial Course', 'Φροντιστηριακό Μάθημα')], null=True)),
                ('hours_per_week', models.IntegerField(null=True)),
                ('no_weeks', models.IntegerField(null=True)),
                ('have_contract', models.BooleanField(null=True)),
                ('comments', models.TextField(null=True)),
                ('approved_by_faculty', models.BooleanField(default=False, null=True)),
                ('approved_date', models.DateField(blank=True, null=True)),
                ('candidate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myprofile.phdstudent')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='curricula.course')),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myprofile.staffmember')),
            ],
        ),
    ]
