# Generated by Django 5.0.3 on 2024-04-01 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curricula', '0009_director'),
        ('myprofile', '0011_alter_associate_fathers_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_gr', models.CharField(max_length=300, null=True)),
                ('title_en', models.CharField(max_length=300, null=True)),
                ('abstract', models.TextField(null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('is_offered', models.BooleanField(default=True, null=True)),
                ('member1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thesis_member1', to='myprofile.staffmember')),
                ('member2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thesis_member2', to='myprofile.staffmember')),
                ('offered_in', models.ManyToManyField(to='curricula.studyprogram')),
                ('supervisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myprofile.staffmember')),
            ],
        ),
    ]
