# Generated by Django 5.0.3 on 2024-04-04 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0015_student_display_name'),
        ('theses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesis',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myprofile.student'),
        ),
    ]
