# Generated by Django 5.0.4 on 2024-04-05 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theses', '0002_thesis_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesis',
            name='assigned_to_char',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
