# Generated by Django 5.0.4 on 2024-04-06 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theses', '0003_thesis_assigned_to_char'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesis',
            name='assignment_ga',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='thesis',
            name='grade_avg',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thesis',
            name='grade_member1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thesis',
            name='grade_member2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thesis',
            name='grade_sup',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thesis',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
