# Generated by Django 5.0.4 on 2024-04-07 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theses', '0004_thesis_assignment_ga_thesis_grade_avg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesis',
            name='assignment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='assigned_to_char',
            field=models.CharField(blank=True, help_text='Πληκτρολογείστε τουλάχιστον τρεις χαρακτήρες', max_length=300, null=True),
        ),
    ]
