# Generated by Django 5.0.3 on 2024-04-08 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theses', '0004_thesis_assignment_ga_thesis_grade_avg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesis',
            name='assigned_to_char',
            field=models.CharField(blank=True, help_text='Πληκτρολογείστε τουλάχιστον τρεις χαρακτήρες', max_length=300, null=True),
        ),
    ]
