# Generated by Django 5.0.3 on 2024-04-08 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theses', '0005_alter_thesis_assigned_to_char'),
        ('theses', '0005_thesis_assignment_date_alter_thesis_assigned_to_char'),
    ]

    operations = [
    ]
