# Generated by Django 5.0.3 on 2024-03-29 15:02

import django.db.models.deletion
import myprofile.directories
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myprofile', '0011_alter_associate_fathers_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(null=True)),
                ('is_editable', models.BooleanField(default=True, null=True)),
                ('end_date', models.DateField(null=True)),
                ('description', models.TextField(null=True)),
                ('country', models.CharField(max_length=200, null=True)),
                ('city', models.CharField(max_length=200, null=True)),
                ('organization', models.CharField(blank=True, max_length=200, null=True)),
                ('funding_required', models.BooleanField(null=True)),
                ('project_title', models.CharField(blank=True, max_length=200, null=True)),
                ('project_acronym', models.CharField(blank=True, max_length=200, null=True)),
                ('project_code', models.CharField(blank=True, max_length=20, null=True)),
                ('travel_expenses', models.FloatField(blank=True, null=True)),
                ('stay_expenses', models.FloatField(blank=True, null=True)),
                ('registration_expenses', models.FloatField(blank=True, null=True)),
                ('ga_document', models.FileField(blank=True, null=True, upload_to=myprofile.directories.leave_dir)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('applicant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myprofile.staffmember')),
            ],
        ),
    ]
