# Generated by Django 5.0.3 on 2024-03-31 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='approved_ga',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
