# Generated by Django 5.0.3 on 2024-03-31 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0002_leave_approved_ga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='project_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
