# Generated by Django 5.0.3 on 2024-03-31 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0003_alter_leave_project_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='funding_required',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
