"""
Django settings for myfaculty project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import ldap
from django_auth_ldap.config import LDAPSearch
import os, json
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-4+1-fx(l&4z82a%cs(1*%#k!3p-mz9*jm1m1+7-7mgpx19j6)_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '192.168.2.109', '192.168.2.10', '10.100.59.214', 'mydep.ditapps.hua.gr', '0.0.0.0']
CSRF_TRUSTED_ORIGINS = ['https://mydep.ditapps.hua.gr']
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_TMP_EXPORT = BASE_DIR / 'media/export/tmp'

if not os.path.isdir(MEDIA_TMP_EXPORT): 
        os.makedirs(MEDIA_TMP_EXPORT)
    
STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR/'static'


CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# Application definition

INSTALLED_APPS = [
    'django_extensions',
    'dal',
    'dal_select2',
    'myprofile.apps.MyprofileConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'crispy_forms',
    'crispy_bootstrap5',
    'rest_framework',
    'rest_framework.authtoken',
    'api',
    'associates',
    'curricula',
    'export',
    'projects',
    'leaves',
    'timesheets',
    'theses',
    'phds'
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myfaculty.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myfaculty.wsgi.application'


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTHENTICATION_BACKENDS = [
    "django_auth_ldap.backend.LDAPBackend",
    "django.contrib.auth.backends.ModelBackend",
]

LOGIN_REDIRECT_URL='/'

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'el-gr'

TIME_ZONE = 'Europe/Athens'

#USE_I18N = True

USE_TZ = True

USE_L10N = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

DATE_FORMAT = '%d/%m/%Y'
DATE_INPUT_FORMATS = ['%d/%m/%Y']


LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {"console": {"class": "logging.StreamHandler"}},
    "loggers": {"django_auth_ldap": {"level": "DEBUG", "handlers": ["console"]}},
}

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('POSTGRES_NAME'),
	'USER': os.environ.get('POSTGRES_USER'),
	'PASSWORD': os.environ.get('POSTGRES_PASSWORD'),
        'HOST': os.environ.get('POSTGRES_HOST'),
        'PORT': '',
    }
}

AUTH_LDAP_SERVER_URI = os.environ.get('AUTH_LDAP_SERVER_URI')
AUTH_LDAP_BIND_DN = os.environ.get('AUTH_LDAP_BIND_DN')
AUTH_LDAP_BIND_PASSWORD = os.environ.get('AUTH_LDAP_BIND_PASSWORD')
AUTH_LDAP_USER_SEARCH = LDAPSearch(
    "dc=hua,dc=gr", ldap.SCOPE_SUBTREE, "(uid=%(user)s)"
)
print("\nEnvironment Variables:\n"+json.dumps(dict(os.environ), indent=2)+"\n")
AUTH_LDAP_USER_ATTR_MAP = {
    "first_name": "givenName",
    "last_name": "sn",
    "email":"email"
}
AUTH_LDAP_START_TLS = True
AUTH_LDAP_GLOBAL_OPTIONS ={
    ldap.OPT_X_TLS_REQUIRE_CERT : ldap.OPT_X_TLS_NEVER 
}

ECTS_GR_TEMPLATE = 'ects_gr'
ECTS_EN_TEMPLATE = 'ects_en'
PROPOSAL_TEMPLATE = 'proposal'
LEAVE_TEMPLATE = 'leave_template'

# Mailer settings
ALWAYS_NOTIFY = 'ditdean@hua.gr,itsec@hua.gr'
DEAN_EMAIL = 'thkam@hua.gr'
EMAIL_PLATFORM_URL = 'https://mydep.ditapps.hua.gr'

# SIS settings
STUD_IP = os.environ.get('STUD_IP')
STUD_USER = os.environ.get('STUD_USER')
STUD_PASSWORD = os.environ.get('STUD_PASSWORD')
STUD_DATABASE = os.environ.get('STUD_DATABASE')
