# Generated by Django 5.0.2 on 2024-02-18 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myprofile', '0006_associate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_no', models.CharField(max_length=40)),
                ('date_time', models.DateTimeField()),
                ('check_type', models.CharField(choices=[('in', 'Είσοδος'), ('out', 'Έξοδος')], max_length=40)),
                ('associate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myprofile.associate')),
            ],
        ),
    ]
