# Generated by Django 5.0.2 on 2024-03-08 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_no', models.CharField(max_length=40)),
                ('updated_time', models.DateTimeField()),
            ],
        ),
    ]
