# Generated by Django 5.0.3 on 2024-03-16 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_gr', models.CharField(max_length=100)),
                ('short_gr', models.CharField(blank=True, max_length=20, null=True)),
                ('code_gr', models.CharField(blank=True, max_length=20, null=True)),
                ('title_en', models.CharField(max_length=100)),
                ('short_en', models.CharField(blank=True, max_length=20, null=True)),
                ('code_en', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_gr', models.CharField(max_length=100)),
                ('short_gr', models.CharField(blank=True, max_length=20, null=True)),
                ('code_gr', models.CharField(blank=True, max_length=20, null=True)),
                ('title_en', models.CharField(max_length=100)),
                ('short_en', models.CharField(blank=True, max_length=20, null=True)),
                ('code_en', models.CharField(blank=True, max_length=20, null=True)),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='curricula.school')),
            ],
        ),
        migrations.CreateModel(
            name='StudyProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_gr', models.CharField(max_length=100)),
                ('short_gr', models.CharField(blank=True, max_length=20, null=True)),
                ('code_gr', models.CharField(blank=True, max_length=20, null=True)),
                ('type_gr', models.CharField(choices=[('Προπτυχιακό', 'Προπτυχιακό'), ('Μεταπτυχιακό', 'Μεταπτυχιακό'), ('Διδακτορικό', 'Διδακτορικό'), ('Μεταδιδακτορικό', 'Μεταδιδακτορικό'), ('´Άλλο', '´Άλλο')], max_length=100)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='curricula.department')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_gr', models.CharField(max_length=20)),
                ('code_en', models.CharField(max_length=20)),
                ('semester', models.IntegerField()),
                ('title_gr', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200)),
                ('weekly_hours', models.IntegerField()),
                ('ects_credits', models.IntegerField()),
                ('type_gr', models.CharField(max_length=100)),
                ('type_en', models.CharField(max_length=100)),
                ('prequesites_gr', models.TextField(blank=True, null=True)),
                ('prequesites_en', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, max_length=300, null=True)),
                ('language_gr', models.CharField(max_length=100)),
                ('language_en', models.CharField(max_length=100)),
                ('offered_erasmus', models.BooleanField(default=False, null=True)),
                ('outcomes_gr', models.TextField(null=True)),
                ('outcomes_en', models.TextField(null=True)),
                ('skills_gr', models.TextField(null=True)),
                ('skills_en', models.TextField(null=True)),
                ('content_gr', models.TextField(null=True)),
                ('content_en', models.TextField(null=True)),
                ('delivery_gr', models.CharField(max_length=200)),
                ('delivery_en', models.CharField(max_length=200)),
                ('ict_gr', models.TextField(null=True)),
                ('ict_en', models.TextField(null=True)),
                ('program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='curricula.studyprogram')),
            ],
        ),
    ]
