# Generated by Django 5.0.3 on 2024-03-17 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curricula', '0001_initial'),
        ('myprofile', '0011_alter_associate_fathers_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='assigned_to',
            field=models.ManyToManyField(to='myprofile.staffmember'),
        ),
        migrations.AddField(
            model_name='course',
            name='display_name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='elective',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='hours_lab',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='hours_lab_prep',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='hours_lecturing',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='hours_project',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='hours_study',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='hours_total',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='weekly_lab_hours',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='ects_credits',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='weekly_hours',
            field=models.IntegerField(null=True),
        ),
    ]
