# Generated by Django 5.0.3 on 2024-03-17 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curricula', '0002_course_assigned_to_course_display_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studyprogram',
            old_name='type_gr',
            new_name='type',
        ),
        migrations.AddField(
            model_name='studyprogram',
            name='code_en',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studyprogram',
            name='short_en',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studyprogram',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
