# Generated by Django 5.0.3 on 2024-03-17 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curricula', '0003_rename_type_gr_studyprogram_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='bibliography_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='bibliography_gr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='journals',
            field=models.TextField(null=True),
        ),
    ]
