# Generated by Django 5.0.3 on 2024-03-17 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curricula', '0004_course_bibliography_en_course_bibliography_gr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='active',
            field=models.BooleanField(null=True),
        ),
    ]
