# Generated by Django 5.0.3 on 2024-03-17 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curricula', '0005_course_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='ects_credits',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='hours_lab',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='hours_lab_prep',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='hours_lecturing',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='hours_project',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='hours_study',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='hours_total',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='weekly_hours',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='weekly_lab_hours',
            field=models.FloatField(null=True),
        ),
    ]
