# Generated by Django 5.0.3 on 2024-04-03 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curricula', '0009_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyprogram',
            name='sis_code',
            field=models.IntegerField(null=True),
        ),
    ]
