# Generated by Django 5.0.3 on 2024-04-08 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curricula', '0010_studyprogram_sis_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='required_lab',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='required_math',
            field=models.TextField(blank=True, null=True),
        ),
    ]
