# Generated by Django 5.0 on 2024-02-06 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('given_name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=70)),
                ('fathers_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('display_name', models.CharField(blank=True, max_length=150, null=True)),
                ('display_name_full', models.CharField(blank=True, max_length=200, null=True)),
                ('tin', models.CharField(max_length=50, null=True)),
                ('ssn', models.CharField(max_length=50, null=True)),
                ('is_internal', models.BooleanField(null=True)),
                ('institution', models.CharField(default='Χαροκόπειο Πανεπιστήμιο', max_length=100)),
                ('school', models.CharField(default='Ψηφιακής Τεχνολογίας', max_length=100)),
                ('title', models.CharField(max_length=70, null=True)),
                ('home_address_street', models.CharField(max_length=70, null=True)),
                ('home_address_no', models.IntegerField(null=True)),
                ('home_address_po_box', models.CharField(max_length=30, null=True)),
                ('home_address_city', models.CharField(max_length=70, null=True)),
                ('home_address_country', models.CharField(max_length=70, null=True)),
                ('mobile_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('home_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('work_address_street', models.CharField(default='Ομήρου', max_length=70, null=True)),
                ('work_address_no', models.CharField(default='9', max_length=10, null=True)),
                ('work_address_po_box', models.CharField(default='17778', max_length=30, null=True)),
                ('work_address_city', models.CharField(default='Αθήνα', max_length=70, null=True)),
                ('work_address_country', models.CharField(default='Ελλάδα', max_length=70, null=True)),
                ('work_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
