# Generated by Django 5.0 on 2024-02-06 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='department',
            field=models.CharField(default='Πληροφορικής και Τηλεματικής', max_length=100),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='is_internal',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
