# Generated by Django 5.0 on 2024-02-06 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0002_staffmember_department_alter_staffmember_is_internal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmember',
            name='home_address_country',
            field=models.CharField(default='Ελλάδα', max_length=70, null=True),
        ),
    ]
