# Generated by Django 5.0.1 on 2024-02-08 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0003_alter_staffmember_home_address_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='pic',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
