# Generated by Django 5.0.1 on 2024-02-16 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0004_staffmember_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmember',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='ssn',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='tin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
