# Generated by Django 5.0.2 on 2024-02-18 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0005_alter_staffmember_pic_alter_staffmember_ssn_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Associate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('given_name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=70)),
                ('fathers_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('display_name', models.CharField(blank=True, max_length=150, null=True)),
                ('display_name_full', models.CharField(blank=True, max_length=200, null=True)),
                ('is_phd_student', models.BooleanField(default=False, null=True)),
                ('is_postdoc', models.BooleanField(default=True, null=True)),
                ('home_address_street', models.CharField(max_length=70, null=True)),
                ('home_address_no', models.IntegerField(null=True)),
                ('home_address_po_box', models.CharField(max_length=30, null=True)),
                ('home_address_city', models.CharField(default='Αθήνα', max_length=70, null=True)),
                ('home_address_country', models.CharField(default='Ελλάδα', max_length=70, null=True)),
                ('mobile_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('home_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('card_no', models.CharField(blank=True, max_length=40, null=True)),
                ('seat_no', models.CharField(blank=True, max_length=40, null=True)),
                ('office_no', models.CharField(blank=True, max_length=40, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
