# Generated by Django 5.0.2 on 2024-02-27 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0006_associate'),
    ]

    operations = [
        migrations.AddField(
            model_name='associate',
            name='ssn',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='associate',
            name='tin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='associate',
            name='work_phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
