# Generated by Django 5.0.2 on 2024-03-01 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0007_associate_ssn_associate_tin_associate_work_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUserPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('is_secreteriat', 'Is a secreteriat user'),),
            },
        ),
    ]
