# Generated by Django 5.0.2 on 2024-03-08 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0008_customuserpermissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='associate',
            name='supervisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myprofile.staffmember'),
        ),
    ]
