# Generated by Django 5.0.2 on 2024-03-10 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0009_associate_supervisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associate',
            name='is_postdoc',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
