# Generated by Django 5.0.3 on 2024-03-16 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0010_alter_associate_is_postdoc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associate',
            name='fathers_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='associate',
            name='home_address_city',
            field=models.CharField(blank=True, default='Αθήνα', max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='associate',
            name='home_address_country',
            field=models.CharField(blank=True, default='Ελλάδα', max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='associate',
            name='home_address_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='associate',
            name='home_address_po_box',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='associate',
            name='home_address_street',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='associate',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myprofile.staffmember'),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='fathers_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
