# Generated by Django 5.0.3 on 2024-04-01 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0011_alter_associate_fathers_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmember',
            name='home_address_city',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='home_address_country',
            field=models.CharField(blank=True, default='Ελλάδα', max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='home_address_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='home_address_po_box',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='home_address_street',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
