# Generated by Django 5.0.3 on 2024-04-03 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curricula', '0009_director'),
        ('myprofile', '0012_alter_staffmember_home_address_city_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usnermae', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('given_name', models.CharField(max_length=50, null=True)),
                ('surname', models.CharField(max_length=70, null=True)),
                ('semester', models.IntegerField(null=True)),
                ('reg_num', models.CharField(max_length=70, null=True)),
                ('program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='curricula.studyprogram')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
