# Generated by Django 5.0.3 on 2024-04-03 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0013_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='usnermae',
            new_name='username',
        ),
    ]
