# Generated by Django 5.0.3 on 2024-04-03 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0014_rename_usnermae_student_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='display_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
