# Generated by Django 5.1.4 on 2025-01-01 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0015_student_display_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhdStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=200, null=True)),
                ('reg_num', models.CharField(max_length=70, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('given_name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=70)),
                ('fathers_name', models.CharField(blank=True, max_length=50)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('external_email', models.EmailField(max_length=254, null=True)),
                ('gender', models.CharField()),
                ('mobile_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('home_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('home_address_street', models.CharField(blank=True, max_length=70, null=True)),
                ('subject_gr', models.CharField()),
                ('subject_en', models.CharField()),
                ('inscription_date', models.DateField()),
                ('inscription_ref', models.CharField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('cv_gr', models.TextField()),
                ('cv_en', models.TextField()),
                ('scopus_id', models.CharField()),
                ('member1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='committee_member1_students', to='myprofile.staffmember')),
                ('member2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='committee_member2_students', to='myprofile.staffmember')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_students', to='myprofile.staffmember')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
