# Generated by Django 5.0.3 on 2024-03-31 10:00

import django.db.models.deletion
import myprofile.directories
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myprofile', '0011_alter_associate_fathers_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(default=3)),
                ('year', models.IntegerField(default=2024)),
                ('unsigned', models.FileField(null=True, upload_to=myprofile.directories.timesheets_dir)),
                ('signed', models.FileField(blank=True, null=True, upload_to=myprofile.directories.timesheets_dir)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('applicant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myprofile.staffmember')),
            ],
        ),
    ]
