# Generated by Django 5.0.3 on 2024-03-31 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='month',
            field=models.IntegerField(default=3, null=True),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='year',
            field=models.IntegerField(default=2024, null=True),
        ),
    ]
