# Generated by Django 5.0.3 on 2024-04-01 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0002_alter_timesheet_month_alter_timesheet_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='month',
            field=models.IntegerField(default=4, null=True),
        ),
    ]
