# Generated by Django 5.1.4 on 2024-12-05 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0003_alter_timesheet_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='month',
            field=models.IntegerField(default=12, null=True),
        ),
    ]
