# Generated by Django 5.1.4 on 2025-01-01 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0004_alter_timesheet_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='month',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='year',
            field=models.IntegerField(default=2025, null=True),
        ),
    ]
