# Generated by Django 5.1.5 on 2025-02-26 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0005_alter_timesheet_month_alter_timesheet_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='month',
            field=models.IntegerField(default=2, null=True),
        ),
    ]
