# Generated by Django 5.1.7 on 2025-04-01 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0007_alter_timesheet_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='month',
            field=models.IntegerField(default=4, null=True),
        ),
    ]
