# Generated by Django 5.0.3 on 2024-03-25 10:38

import django.db.models.deletion
import myprofile.directories
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myprofile', '0011_alter_associate_fathers_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_editable', models.BooleanField(blank=True, default=True, null=True)),
                ('appoved', models.BooleanField(blank=True, default=False, null=True)),
                ('submission_approved_ga', models.CharField(blank=True, max_length=100, null=True)),
                ('implementation_approved_ga', models.CharField(blank=True, max_length=100, null=True)),
                ('budget_total', models.FloatField(null=True)),
                ('budget_dep', models.FloatField(null=True)),
                ('call', models.TextField(null=True)),
                ('thematic_areas', models.TextField(null=True)),
                ('title', models.TextField(null=True)),
                ('department_role', models.TextField(null=True)),
                ('department_staff', models.TextField(null=True)),
                ('acronym', models.CharField(blank=True, max_length=100, null=True)),
                ('abstract', models.TextField(null=True)),
                ('partners', models.TextField(null=True)),
                ('funding_date', models.FloatField(default=100, null=True)),
                ('duration', models.FloatField(null=True)),
                ('start', models.DateField(null=True)),
                ('document_approved_submission', models.FileField(upload_to=myprofile.directories.project_dir)),
                ('document_approved_implementation', models.FileField(upload_to=myprofile.directories.project_dir)),
                ('coordinator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myprofile.staffmember')),
            ],
        ),
    ]
