# Generated by Django 5.0.3 on 2024-03-26 13:51

import myprofile.directories
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='crated_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='document_approved_implementation',
            field=models.FileField(blank=True, null=True, upload_to=myprofile.directories.project_dir),
        ),
        migrations.AlterField(
            model_name='project',
            name='document_approved_submission',
            field=models.FileField(blank=True, null=True, upload_to=myprofile.directories.project_dir),
        ),
    ]
