# Generated by Django 5.0.3 on 2024-03-26 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_crated_date_project_updated_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='crated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='updated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
