# Generated by Django 5.0.3 on 2024-03-26 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_crated_date_alter_project_updated_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='crated_date',
            new_name='created_date',
        ),
    ]
