# Generated by Django 5.0.3 on 2024-03-27 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_rename_crated_date_project_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='submission_date',
            field=models.DateField(null=True),
        ),
    ]
