# Generated by Django 5.0.3 on 2024-03-27 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_submission_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='appoved',
            new_name='approved',
        ),
    ]
