# Generated by Django 5.1.4 on 2024-12-05 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_rename_appoved_project_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='submission_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
